In [1]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])



In [2]:
result = np.vstack((array1, array2))
print(result)


[[ 1  2]
 [ 3  4]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [8]:
a = np.array([10, 20, 30, 40, 50])
print(a.where(20))  # Output: (array([2, 3, 4]),)


AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [9]:
import numpy as np

def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j + 1] = temp
    return array

my_array = np.array([20, 14, 25, 16, 45, 60, 12, 9])
sorted_array = bub_sort(my_array)
print(sorted_array)


[60 45 25 20 16 14 12  9]


In [11]:
import numpy as np

Sample = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12],
                   [13, 14, 15]])

result = Sample[:4, [1]]
print(result)


[[ 2]
 [ 5]
 [ 8]
 [11]]


In [13]:
np.arange(20,2)

array([], dtype=int32)

In [14]:
import numpy as np

array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])


In [15]:
result = np.concatenate((array1, array2), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [16]:
result = np.hstack((array1, array2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [17]:
import numpy as np

# Given vectors
A = np.array([[4], [12], [29]])
B = np.array([[13], [21], [4]])

# Flatten the vectors
A_flat = A.flatten()
B_flat = B.flatten()

# Compute the cross product
cross_product = np.cross(A_flat, B_flat)
print(cross_product)


[-561  361  -72]


In [18]:
import numpy as np

A = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25])
B = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(A, B)

# Extract the correlation coefficient between A and B
correlation_coefficient = corr_matrix[0, 1]
print(correlation_coefficient)


1.0


In [19]:
corr_matrix

array([[1., 1.],
       [1., 1.]])

In [20]:
import numpy as np

sample = {
    1: [1, 2],
    2: [[1], [2]],
    3: [[1, 2], [3, 4], [4, 5]],
    4: [1],
    5: [1, 2, 3, 4, 5]
}

# Convert dictionary values to NumPy arrays
arrays = [np.array(value) for value in sample.values()]

# Create a nested NumPy array
nested_array = np.array(arrays, dtype=object)  # dtype=object to handle arrays of different shapes
print(nested_array)


[array([1, 2]) array([[1],
                      [2]]) array([[1, 2],
                                   [3, 4],
                                   [4, 5]]) array([1])
 array([1, 2, 3, 4, 5])]


In [22]:
import numpy as np

# Create the array
N = np.array([99, None, 49, np.nan, 'str', np.nan, 63, 50, (), [], {}, '...', ''])

# Find the number of elements
num_elements = N.size
print(num_elements)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (13,) + inhomogeneous part.

In [23]:
a=np.array([1,2,4,5])

In [24]:
len(a)

4

In [25]:
a.size

4

In [26]:
a.count

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [27]:
np.size(a)

4

In [31]:
job = "analyst"

# Using indexing
# last_char_index = job[7]1


# Using length and indexing
last_char_length = job[len(job) - 1]

# Using negative indexing
last_char_negative = job[-1]

# Print results
# print(f"Last character using job[7]: {last_char_index}")
print(f"Last character using job[len(job) - 1]: {last_char_length}")
print(f"Last character using job[-1]: {last_char_negative}")


Last character using job[len(job) - 1]: t
Last character using job[-1]: t


In [32]:
job[5:6]

's'

In [35]:
a= np.array([[1,2,4],[4,7,8],[1,2,3]])

In [36]:
np.sum(a,axis=1)

array([ 7, 19,  6])